/* Auto-generated by tools/gen_books.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

typedef struct {
    const char *name;
    const uint8_t *data;
    uint32_t len;
} embedded_book_t;

extern const embedded_book_t embedded_books[];
extern const int embedded_books_count;
