/* Auto-generated by tools/gen_font.py — DO NOT EDIT */
#pragma once
#include <stdint.h>
#define ASCII_FONT_COUNT 96
#define GB2312_GRID_ROWS 94
#define GB2312_GRID_COLS 94
#define GB2312_CHAR_COUNT 7445
extern const uint8_t ascii8x16_font[96 * 16];
extern const uint8_t gb2312_16_font[94 * 94 * 32];
extern const uint32_t gb2312_cp_table[7445];
extern const uint16_t gb2312_idx_table[7445];
