/* Auto-generated by tools/gen_pinyin.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

typedef struct { const char *pinyin; const char *chars; } py_entry_t;
extern const py_entry_t pinyin_table[];
extern const int pinyin_table_count;
