#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_font.py — 生成 GB2312 16x16 点阵字库 + ASCII 8x16 字库 (C 数组)
用法: python tools/gen_font.py
输出: main/font_data.h, main/font_data.c
依赖: pillow (pip install pillow)
字体: 系统 SimSun (可换 simhei.ttf)
"""
import os
import sys

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, "..", "main", "font_data.h")
OUT_C = os.path.join(HERE, "..", "main", "font_data.c")

FONT_PATH = r"C:\Windows\Fonts\simsun.ttc"
FONT_SIZE = 16

ASCII_COUNT = 96   # 0x20..0x7F
GB_ROWS = 94
GB_COLS = 94
GB_TOTAL = GB_ROWS * GB_COLS


def char_bitmap(ch, w, h, font):
    """渲染单字符为 w x h 的 1bpp 位图, 返回 h 行字节列表"""
    img = Image.new("L", (w, h), 0)
    d = ImageDraw.Draw(img)
    d.text((0, 0), ch, font=font, fill=255)
    px = img.load()
    rows = []
    for y in range(h):
        byte = 0
        for x in range(w):
            byte = (byte << 1) | (1 if px[x, y] > 127 else 0)
        rows.append(byte)
    return rows


def main():
    if not os.path.exists(FONT_PATH):
        print("font not found:", FONT_PATH)
        sys.exit(1)
    font = ImageFont.truetype(FONT_PATH, FONT_SIZE)

    # ---- ASCII 8x16 ----
    ascii_data = bytearray()
    for c in range(0x20, 0x7F):
        rows = char_bitmap(chr(c), 8, 16, font)
        ascii_data += bytes(rows)
    # 0x7F 用空白补齐, 保持 96 项
    ascii_data += bytes(16)

    # ---- GB2312 94x94 ----
    gb_data = bytearray()
    found = 0
    cp_list = []   # (unicode_cp, grid_index) 供固件 UTF-8 查找
    for q in range(1, GB_ROWS + 1):
        for w in range(1, GB_COLS + 1):
            hi, lo = 0xA0 + q, 0xA0 + w
            try:
                ch = bytes([hi, lo]).decode("gb2312")
            except UnicodeDecodeError:
                gb_data += bytes(32)
                continue
            rows = char_bitmap(ch, 16, 16, font)
            for r in rows:
                gb_data += bytes([r >> 8, r & 0xFF])
            cp_list.append((ord(ch), (q - 1) * GB_COLS + (w - 1)))
            found += 1

    cp_list.sort()
    cp_table = [c for c, _ in cp_list]
    idx_table = [i for _, i in cp_list]

    print(f"ASCII: {ASCII_COUNT} chars, GB2312: {found}/{GB_TOTAL} chars")

    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by tools/gen_font.py — DO NOT EDIT */\n")
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write("#define ASCII_FONT_COUNT %d\n" % ASCII_COUNT)
        f.write("#define GB2312_GRID_ROWS %d\n" % GB_ROWS)
        f.write("#define GB2312_GRID_COLS %d\n" % GB_COLS)
        f.write("#define GB2312_CHAR_COUNT %d\n" % found)
        f.write("extern const uint8_t ascii8x16_font[%d * 16];\n" % ASCII_COUNT)
        f.write("extern const uint8_t gb2312_16_font[%d * %d * 32];\n" % (GB_ROWS, GB_COLS))
        f.write("extern const uint32_t gb2312_cp_table[%d];\n" % found)
        f.write("extern const uint16_t gb2312_idx_table[%d];\n" % found)

    with open(OUT_C, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by tools/gen_font.py — DO NOT EDIT */\n")
        f.write('#include "font_data.h"\n\n')
        f.write("const uint8_t ascii8x16_font[%d * 16] = {\n" % ASCII_COUNT)
        for i in range(0, len(ascii_data), 12):
            f.write("    " + ", ".join("0x%02X" % b for b in ascii_data[i:i + 12]) + ",\n")
        f.write("};\n\n")
        f.write("const uint8_t gb2312_16_font[%d * %d * 32] = {\n" % (GB_ROWS, GB_COLS))
        for i in range(0, len(gb_data), 12):
            f.write("    " + ", ".join("0x%02X" % b for b in gb_data[i:i + 12]) + ",\n")
        f.write("};\n\n")
        f.write("const uint32_t gb2312_cp_table[%d] = {\n" % found)
        for i in range(0, len(cp_table), 10):
            f.write("    " + ", ".join("0x%04X" % c for c in cp_table[i:i + 10]) + ",\n")
        f.write("};\n\n")
        f.write("const uint16_t gb2312_idx_table[%d] = {\n" % found)
        for i in range(0, len(idx_table), 12):
            f.write("    " + ", ".join("%d" % v for v in idx_table[i:i + 12]) + ",\n")
        f.write("};\n")

    print("written:", OUT_H)
    print("written:", OUT_C)


if __name__ == "__main__":
    main()
