#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_books.py — 将 storage_data/books/*.txt 编译进固件 (内置电子书)
输出: ../main/books_data.h, ../main/books_data.c
"""
import glob
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "storage_data", "books")
OUT_H = os.path.join(HERE, "..", "main", "books_data.h")
OUT_C = os.path.join(HERE, "..", "main", "books_data.c")

files = sorted(glob.glob(os.path.join(SRC, "*.txt")))
if not files:
    print("no books found in", SRC)
    raise SystemExit(1)

with open(OUT_H, "w", encoding="utf-8") as f:
    f.write("/* Auto-generated by tools/gen_books.py — DO NOT EDIT */\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("typedef struct {\n    const char *name;\n    const uint8_t *data;\n    uint32_t len;\n} embedded_book_t;\n\n")
    f.write("extern const embedded_book_t embedded_books[];\n")
    f.write("extern const int embedded_books_count;\n")

with open(OUT_C, "w", encoding="utf-8") as f:
    f.write("/* Auto-generated by tools/gen_books.py — DO NOT EDIT */\n")
    f.write('#include "books_data.h"\n\n')
    arrs = []
    entries = []
    for i, path in enumerate(files):
        name = os.path.basename(path)
        data = open(path, "rb").read()
        arr = "embedded_book_%d" % i
        f.write("static const uint8_t %s[] = {\n" % arr)
        for j in range(0, len(data), 12):
            f.write("    " + ", ".join("0x%02X" % b for b in data[j:j + 12]) + ",\n")
        f.write("};\n\n")
        arrs.append(arr)
        entries.append('    { "%s", %s, %d }, /* %s */' % (name, arr, len(data), os.path.basename(path)))
    f.write("const embedded_book_t embedded_books[] = {\n")
    f.write("\n".join(entries) + "\n};\n\n")
    f.write("const int embedded_books_count = %d;\n" % len(files))

print("books embedded:", len(files))
for p in files:
    print("  ", os.path.basename(p), os.path.getsize(p), "bytes")
