#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_pinyin.py — 生成拼音输入法词库 (拼音 -> GB2312 汉字列表)
输出: ../main/pinyin_data.h, ../main/pinyin_data.c
"""
import os
import sys

from pypinyin import lazy_pinyin

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, "..", "main", "pinyin_data.h")
OUT_C = os.path.join(HERE, "..", "main", "pinyin_data.c")

# GB2312 全字符
chars = set()
for q in range(1, 95):
    for w in range(1, 95):
        try:
            chars.add(bytes([0xA0 + q, 0xA0 + w]).decode("gb2312"))
        except UnicodeDecodeError:
            pass

table = {}   # pinyin -> list of chars
for ch in sorted(chars):
    try:
        py = lazy_pinyin(ch)[0]
    except Exception:
        continue
    py = py.lower()
    if not py or not py.isalpha():
        continue
    table.setdefault(py, []).append(ch)

# 只保留 <32 个候选的常用拼音 (候选栏一页显示有限)
items = sorted((py, cs) for py, cs in table.items() if len(cs) <= 24)
print("pinyin entries:", len(items), "/", len(table))

with open(OUT_H, "w", encoding="utf-8") as f:
    f.write("/* Auto-generated by tools/gen_pinyin.py — DO NOT EDIT */\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("typedef struct { const char *pinyin; const char *chars; } py_entry_t;\n")
    f.write("extern const py_entry_t pinyin_table[];\n")
    f.write("extern const int pinyin_table_count;\n")

with open(OUT_C, "w", encoding="utf-8") as f:
    f.write("/* Auto-generated by tools/gen_pinyin.py — DO NOT EDIT */\n")
    f.write('#include "pinyin_data.h"\n\n')
    f.write("const py_entry_t pinyin_table[] = {\n")
    for py, cs in items:
        s = "".join(cs)
        f.write('    { "%s", "%s" },\n' % (py, s))
    f.write("};\n\n")
    f.write("const int pinyin_table_count = %d;\n" % len(items))

print("written:", OUT_H, OUT_C)
